# This is the final, corrected blueprint for Render.
# It separates the database definition from the application services.

databases:
  # 1. The PostgreSQL Database Service
  # This is now correctly defined in its own top-level 'databases' section.
  - name: ai-credit-db
    plan: free # Use Render's free tier for the database

services:
  # 2. The Python Backend Service (FastAPI)
  - type: web
    name: ai-credit-backend
    runtime: python
    plan: free
    rootDir: backend
    buildCommand: |
      pip install -r requirements.txt &&
      apt-get update && apt-get install -y tesseract-ocr
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker app.main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromService:
          type: psql # When referencing the database, 'psql' is the correct type.
          name: ai-credit-db
          property: connectionString
      - fromGroup: ai-credit-secrets

  # 3. The Static Frontend Service (HTML/CSS/JS)
  - type: staticSite
    name: ai-credit-frontend
    rootDir: web_frontend
    routes:
      - type: rewrite
        source: /login.html
        destination: /login.html
      - type: rewrite
        source: /customer.html
        destination: /customer.html
      - type: rewrite
        source: /admin.html
        destination: /admin.html
      - type: rewrite
        source: /*
        destination: /index.html

# This section remains the same.
envVarGroups:
  - name: ai-credit-secrets
    envVars:
      - key: SECRET_KEY
        value: "your_super_secret_key_here"
