# This is the final, corrected blueprint for Render.

databases:
  - name: ai-credit-db
    plan: free

services:
  - type: web
    name: ai-credit-backend
    runtime: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    # --- THIS IS THE FIX FOR THE DATABASE RACE CONDITION ---
    # It now runs your new script *before* starting the server.
    startCommand: python create_tables.py && gunicorn -w 4 -k uvicorn.workers.UvicornWorker app.main:app -b 0.0.0.0:8000
    envVars:
      - key: DATABASE_URL
        fromService:
          type: psql
          name: ai-credit-db
          property: connectionString
      - fromGroup: ai-credit-secrets

  - type: staticSite
    name: ai-credit-underwriting-system # This should match your frontend service name
    rootDir: web_frontend
    routes:
      - type: rewrite
        source: /login.html
        destination: /login.html
      - type: rewrite
        source: /customer.html
        destination: /customer.html
      - type: rewrite
        source: /admin.html
        destination: /admin.html
      - type: rewrite
        source: /*
        destination: /index.html

envVarGroups:
  - name: ai-credit-secrets
    envVars:
      - key: SECRET_KEY
        value: "your_super_secret_key_here"
```

### Final Instructions

After updating these three files, please **push all of them to your GitHub repository**.

```bash
git add backend/create_tables.py backend/app/main.py render.yaml
git commit -m "Fix: Final deployment fix for CORS and database race condition"
git push origin main

